%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 4 -*-
---

on:
    push:
        branches:
            -   '*'

jobs:
    job_npm_test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                versions:
                    -   { node:  8, eslint: 7 }
                    -   { node: 10, eslint: 7 }
                    -   { node: 12, eslint: 7 }
                    -   { node: 14, eslint: 7 }
                    -   { node: 16, eslint: 8 }

        steps:
            -   uses: actions/checkout@v2
            -   name: 'Use Node.js ${{ matrix.versions.node }}.x'
                uses: actions/setup-node@v1
                with:
                    node-version: '${{ matrix.versions.node }}.x'

            # The npm from node images before v16 seems to not install
            # Peer dependencies by default, so we have to:
            -   run: npm install eslint@${{ matrix.versions.eslint }}

            -   run: npm install .
            -   run: npm audit
            -   run: npm test


...
